type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Premier League"
      parameters:
        componentName: "Start"
    Premier League:
      type: "modular-api-extract-input-v1"
      parameters:
        componentName: "Premier League"
        inputId: "api-extract-input-v1"
        api-extract-input-v1:
          profile: "custom-a34da799-8276-401d-ad6a-0b52e9b243b7"
          endpoint:
          connectionRef:
            authType:
            overrides: {}
          uriParams:
          queryParams:
          headerParams:
          postBody:
          pageLimit:
        outputId:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Premier League:
      position:
        x: 150
        "y": 0
      tempMetlId: 2
